### ISSUE TITLE
Show keys/legend in export

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/timelapse-colorizer#147]
## Use Case

When exporting, the key or legend should be shown for continuous, discrete, and categorical feature data.

## Acceptance Criteria

- Needs UX work!
- Show an overlay (or sidebar) in the video export.
- For categorical data, it should include the label and the color for each category.
- For continuous/discrete data, it should show the color ramp gradient and a min/max value.

![image](https://github.com/user-attachments/assets/60a841e9-7ca8-4ce4-b572-5c4e47657ae6)

## Questions:
- When should the key/legend be visible?
  - If it's always visible, is it redundant with information that's already shown at the top of the screen?
  - Should users be able to toggle it on or off at any time? What button will show them this? -> could be a chance to revisit the viewer settings, see #303
  - Should users only be able to see it as a preview during Export? How would it be shown to the user?
- Should the scale bar and timestamp live in the legend area too, or stay as an overlay?
- What existing designs are there that we can reference from other papers?
- How should categorical features look vs. continuous features?

**Comment by ShrimpCryptid** [comment]
> Question: Who is currently using video export? Who needs this feature?

Update: Yes, many people (esp. nucmorph project) are using video export.

**Comment by ShrimpCryptid** [comment]
@chantelleleveille specifically may have some thoughts on this when we do a discussion w/ scientists

**Comment by ShrimpCryptid** [comment]
Discussion with Julie:
- Needs color bar with high/low color value + feature label
- If it's too large, don't put in the on-screen inset
- Maybe redundant if it's visible during regular interaction -> maybe show only during export?
- Users would usually want to export with the information
  - Option to hide it *maybe if making a slide*, but usually better for users to have the option
- Okay to add an edge to separate from the rest of the viewport frame

**Comment by ShrimpCryptid** [comment]
Hard deadline before NucMorph final publication

**Comment by toloudis** [comment]
layout for categorical features uses different amount of space vs color ramp features?

**Comment by ShrimpCryptid** [comment]
![Image](https://github.com/user-attachments/assets/5d88922a-5713-4e31-9e08-8bb3942ce1c1)

**Comment by ShrimpCryptid** [comment]
### Questions:
When should the key/legend be visible?
 - If it's always visible, is it redundant with information that's already shown at the top of the screen?
 - Should users be able to toggle it on or off at any time? What button will show them this? -> could be a chance to revisit the Viewer Settings
 - Should users only be able to see it as a preview during Export? How would it be shown to the user?

Should the scale bar and timestamp live in the legend area too, or stay as an overlay?

**Comment by TravisKroeker** [comment]
See links to designs here:
https://www.figma.com/design/DcFEsrszbUOK0qU1E9wrH0/colorizer_UI_components_and_V1_design?node-id=2076-8212&t=A1khuBAHlSBXSRma-1
