### ISSUE TITLE
Glossary for feature descriptions

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/timelapse-colorizer#198]
## Use Case

A possible need/want for publication might be a tab or some space in the UI to display a .md file (or iframed web page?) that has a nice descriptive text about the dataset.  This would help external users who are coming in cold.

This has come up in CFE as well.

Such a document could provide a glossary of what the feature names mean, among other things.

## Acceptance Criteria

**Determine** if this is needed, prioritize, and design an initial layout.  

## Details

I suggest .md to keep it simple, just text and pictures and links.
Who authors the document?  How do they add it to a dataset?
Where does it belong in the layout?

**Comment by ShrimpCryptid** [comment]
- iframe an external markdown file or webpage?
  - @ShrimpCryptid candidate for hacking in

**Comment by toloudis** [comment]
minimum info:  something like a tooltip with ~2 sentences for each feature (#371). -- this might satisfy the more immediate need as of writing this

**Comment by ShrimpCryptid** [comment]
![Image](https://github.com/user-attachments/assets/28c5545f-50c6-4508-b656-919788f920e6)

**Comment by toloudis** [comment]
Also, can there be images?   see https://www.allencell.org/glossary-of-cell-features-v2.html

**Comment by ShrimpCryptid** [comment]
Adding a comment, this was also requested by educators during Teachstravaganza.

**Comment by ShrimpCryptid** [comment]
short description + long description field? (one for tooltip, one for glossary?)

**Comment by toloudis** [comment]
1. links in tooltips are not accessible via keyboard
2. tooltips should be brief but the scientists are concerned that you can not get full accuracy and it might be misleading.  scientists asked that shortened descriptions are not as important as the full description.
3. do we need both tooltips AND a full glossary panel?
4. is a long tooltip really a tooltip? Is there a middle ground where it's a popup modal or something?  At the point of access in the feature dropdown

**Comment by toloudis** [comment]
We will initially implement an expandable panel that is at a higher z index above the rest of the ui.
There will be a button next to the feature dropdown that triggers the panel to open.
Doesnt need to scroll to current feature.

what is the icon?  "glossary"
