### ISSUE TITLE
Load features asynchronously

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/timelapse-colorizer#20]
## Use Case

If I have a dataset with a large number of features, I may not want to consume extra resources by loading them all initially.

## Acceptance Criteria

Only load feature data on-demand.

## Details

Could discard old feature data (or optionally keep around a very limited number of them in a local cache)

**Comment by ShrimpCryptid** [comment]
Starting to see big slowdowns on the nucmorph dataset. May experimentally implement this.

**Comment by ShrimpCryptid** [comment]
Should we close this now that feature load is multithreaded?

**Comment by toloudis** [comment]
I agree we can close it and create a new ticket if we have concerns later.  Binary+worker loading was a big win

**Comment by ShrimpCryptid** [comment]
Closed by #420 and #409, which solve the underlying performance concerns.
