### ISSUE TITLE
Zooming into viewport beyond 250% starts to shrink it instead

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/timelapse-colorizer#234]
![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/98dc3ad9-701d-480e-ab38-f9488817c6af)

Issue submitted by @derekthirstrup. According to Derek, "the image gets smaller above 250% zoom" and "I can't zoom enough to see segmentation of individual cells."

Most visible on this dataset: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fmicroscopy%2FClusterOutput%2FH2B_Deliverable_AnalysisPipelineOutput%2FH2B_Deliverable_InputImages_123Timelapses_Composite_Output%2Fcolorizer%2Fcollection.json

**Comment by toloudis** [comment]
This opens the greater "go to fullscreen" discussion
