### ISSUE TITLE
Visualize XY movement delta

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/timelapse-colorizer#42]
visualization: draw a small vector from current centroid to previous centroid (or next centroid) to indicate how the cell is moving.

**Comment by ShrimpCryptid** [comment]
- Should these be colored with a constant color?
-  Should we change the color by direction? 
- Should length be constant or change based on delta?
- I assume that we can just toggle these with a checkbox.

**Comment by toloudis** [comment]
Here's how I would prototype: since time intervals are constant, the distance from previous to current centroid IS the velocity.  We could start by just using pink lines and drawing them at full length or 1/2 length, just something that looks reasonable. Draw them for all cells in the field at each frame.  The lines would be mutually exclusive with "show track path". Or if we picked some different color, could show both. And yes a show/hide toggle button.  

It would be good to hear from users on whether this would be useful to them. At least one upvote would be nice!

**Comment by ShrimpCryptid** [comment]
Voted useful by Leigh, but maybe also needs to include Z-axis information.
